export interface AssessmentQuestion {
  id: string
  text: string
  type: "scale" | "yesno" | "multiple" | "frequency"
  options?: string[]
  ageRange: [number, number] // 适用月龄范围
  standardRef?: string // 参考标准
  weight?: number // 权重 1-3
}

export interface AssessmentDimension {
  id: string
  name: string
  icon: string
  color: string
  description: string
  questions: AssessmentQuestion[]
}

export interface StageAssessment {
  stageId: string
  stageName: string
  dimensions: AssessmentDimension[]
}

// 0-3岁 感官启蒙期评估题库
export const ASSESSMENT_0_3: StageAssessment = {
  stageId: "0-3",
  stageName: "感官启蒙期",
  dimensions: [
    {
      id: "gross_motor",
      name: "大运动发展",
      icon: "ri-run-line",
      color: "orange",
      description: "身体大肌肉群的运动能力",
      questions: [
        {
          id: "gm_0_3_1",
          text: "能够独立抬头并保持稳定",
          type: "scale",
          ageRange: [0, 6],
          standardRef: "WHO运动标准",
          weight: 3,
        },
        {
          id: "gm_0_3_2",
          text: "能够独立翻身（从仰卧到俯卧）",
          type: "yesno",
          ageRange: [3, 9],
          standardRef: "WHO运动标准",
          weight: 3,
        },
        {
          id: "gm_0_3_3",
          text: "能够独立坐稳（无需支撑）",
          type: "scale",
          ageRange: [5, 10],
          standardRef: "WHO运动标准",
          weight: 3,
        },
        { id: "gm_0_3_4", text: "能够爬行前进", type: "yesno", ageRange: [6, 12], standardRef: "CDC里程碑", weight: 2 },
        {
          id: "gm_0_3_5",
          text: "能够扶物站立",
          type: "scale",
          ageRange: [8, 14],
          standardRef: "WHO运动标准",
          weight: 3,
        },
        {
          id: "gm_0_3_6",
          text: "能够独立行走（至少10步）",
          type: "yesno",
          ageRange: [9, 18],
          standardRef: "WHO运动标准",
          weight: 3,
        },
        {
          id: "gm_0_3_7",
          text: "能够跑步且较少摔倒",
          type: "scale",
          ageRange: [18, 36],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        { id: "gm_0_3_8", text: "能够踢球", type: "yesno", ageRange: [18, 36], standardRef: "CDC里程碑", weight: 1 },
        {
          id: "gm_0_3_9",
          text: "能够双脚跳离地面",
          type: "scale",
          ageRange: [24, 36],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "gm_0_3_10",
          text: "能够上下楼梯（交替脚）",
          type: "scale",
          ageRange: [30, 42],
          standardRef: "Bayley量表",
          weight: 2,
        },
      ],
    },
    {
      id: "fine_motor",
      name: "精细运动发展",
      icon: "ri-hand-coin-line",
      color: "blue",
      description: "手部精细动作能力",
      questions: [
        {
          id: "fm_0_3_1",
          text: "能够握住摇铃等物品",
          type: "scale",
          ageRange: [0, 6],
          standardRef: "Bayley量表",
          weight: 2,
        },
        {
          id: "fm_0_3_2",
          text: "能够把物品从一只手换到另一只手",
          type: "yesno",
          ageRange: [4, 10],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "fm_0_3_3",
          text: "能够用拇指和食指捏起小物品（钳形抓握）",
          type: "scale",
          ageRange: [8, 14],
          standardRef: "WHO标准",
          weight: 3,
        },
        {
          id: "fm_0_3_4",
          text: "能够把物品放入容器中",
          type: "scale",
          ageRange: [10, 16],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "fm_0_3_5",
          text: "能够搭建2-3块积木塔",
          type: "yesno",
          ageRange: [12, 20],
          standardRef: "Bayley量表",
          weight: 2,
        },
        {
          id: "fm_0_3_6",
          text: "能够用笔涂鸦",
          type: "scale",
          ageRange: [12, 24],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "fm_0_3_7",
          text: "能够翻书页（可能多页一起翻）",
          type: "yesno",
          ageRange: [12, 24],
          standardRef: "CDC里程碑",
          weight: 1,
        },
        {
          id: "fm_0_3_8",
          text: "能够搭建6块以上积木塔",
          type: "scale",
          ageRange: [24, 36],
          standardRef: "Bayley量表",
          weight: 2,
        },
        {
          id: "fm_0_3_9",
          text: "能够画出圆形或类似圆形",
          type: "scale",
          ageRange: [30, 42],
          standardRef: "Bayley量表",
          weight: 2,
        },
        {
          id: "fm_0_3_10",
          text: "能够用剪刀剪纸（简单动作）",
          type: "yesno",
          ageRange: [30, 42],
          standardRef: "CDC里程碑",
          weight: 1,
        },
      ],
    },
    {
      id: "language_receptive",
      name: "语言理解",
      icon: "ri-ear-line",
      color: "green",
      description: "理解语言的能力",
      questions: [
        {
          id: "lr_0_3_1",
          text: "对声音有反应（转头、眨眼）",
          type: "scale",
          ageRange: [0, 4],
          standardRef: "听力筛查标准",
          weight: 3,
        },
        {
          id: "lr_0_3_2",
          text: "听到名字会转头看",
          type: "yesno",
          ageRange: [5, 12],
          standardRef: "CDC里程碑",
          weight: 3,
        },
        {
          id: "lr_0_3_3",
          text: '能理解"不可以"',
          type: "scale",
          ageRange: [8, 14],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "lr_0_3_4",
          text: '能理解简单指令（如"把球给我"）',
          type: "scale",
          ageRange: [10, 18],
          standardRef: "MacArthur量表",
          weight: 3,
        },
        {
          id: "lr_0_3_5",
          text: "能指出被命名的物品或图片",
          type: "scale",
          ageRange: [12, 20],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "lr_0_3_6",
          text: "能理解身体部位名称",
          type: "yesno",
          ageRange: [15, 24],
          standardRef: "MacArthur量表",
          weight: 2,
        },
        {
          id: "lr_0_3_7",
          text: '能理解两步指令（如"拿杯子放桌上"）',
          type: "scale",
          ageRange: [24, 36],
          standardRef: "CDC里程碑",
          weight: 3,
        },
        {
          id: "lr_0_3_8",
          text: '能理解"大/小""上/下"等概念',
          type: "scale",
          ageRange: [24, 36],
          standardRef: "MacArthur量表",
          weight: 2,
        },
      ],
    },
    {
      id: "language_expressive",
      name: "语言表达",
      icon: "ri-chat-smile-3-line",
      color: "teal",
      description: "表达语言的能力",
      questions: [
        {
          id: "le_0_3_1",
          text: "会发出咿呀声（元音）",
          type: "scale",
          ageRange: [0, 6],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "le_0_3_2",
          text: "会发出辅音+元音组合（如ba、ma）",
          type: "yesno",
          ageRange: [4, 10],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "le_0_3_3",
          text: '会有意识地叫"爸爸""妈妈"',
          type: "yesno",
          ageRange: [9, 18],
          standardRef: "CDC里程碑",
          weight: 3,
        },
        {
          id: "le_0_3_4",
          text: "能说3个以上的词（除爸妈外）",
          type: "scale",
          ageRange: [12, 20],
          standardRef: "MacArthur量表",
          weight: 3,
        },
        {
          id: "le_0_3_5",
          text: "词汇量达到50个以上",
          type: "yesno",
          ageRange: [18, 30],
          standardRef: "MacArthur量表",
          weight: 2,
        },
        {
          id: "le_0_3_6",
          text: "能说2-3个词的短句",
          type: "scale",
          ageRange: [18, 30],
          standardRef: "CDC里程碑",
          weight: 3,
        },
        {
          id: "le_0_3_7",
          text: "能说出自己的名字",
          type: "yesno",
          ageRange: [24, 36],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "le_0_3_8",
          text: "能进行简单对话",
          type: "scale",
          ageRange: [30, 42],
          standardRef: "MacArthur量表",
          weight: 2,
        },
        {
          id: "le_0_3_9",
          text: "陌生人能听懂大部分话语",
          type: "scale",
          ageRange: [30, 42],
          standardRef: "CDC里程碑",
          weight: 2,
        },
      ],
    },
    {
      id: "social_emotional",
      name: "社会情感",
      icon: "ri-heart-smile-line",
      color: "pink",
      description: "情感和社交发展",
      questions: [
        {
          id: "se_0_3_1",
          text: "会对人微笑（社会性微笑）",
          type: "yesno",
          ageRange: [1, 4],
          standardRef: "CDC里程碑",
          weight: 3,
        },
        {
          id: "se_0_3_2",
          text: "喜欢与照顾者互动玩耍",
          type: "scale",
          ageRange: [2, 8],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "se_0_3_3",
          text: "对陌生人有警惕反应",
          type: "scale",
          ageRange: [6, 12],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "se_0_3_4",
          text: "会玩躲猫猫等互动游戏",
          type: "yesno",
          ageRange: [6, 12],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        { id: "se_0_3_5", text: "有分离焦虑表现", type: "scale", ageRange: [8, 18], standardRef: "ASQ-SE", weight: 2 },
        {
          id: "se_0_3_6",
          text: "会模仿大人的动作",
          type: "scale",
          ageRange: [10, 18],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "se_0_3_7",
          text: "对其他小朋友感兴趣",
          type: "scale",
          ageRange: [18, 30],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "se_0_3_8",
          text: "会进行假装游戏",
          type: "yesno",
          ageRange: [18, 36],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "se_0_3_9",
          text: "能表达自己的情绪",
          type: "scale",
          ageRange: [24, 36],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "se_0_3_10",
          text: "会轮流和分享（在引导下）",
          type: "scale",
          ageRange: [30, 42],
          standardRef: "CDC里程碑",
          weight: 2,
        },
      ],
    },
    {
      id: "self_care",
      name: "生活自理",
      icon: "ri-t-shirt-2-line",
      color: "yellow",
      description: "日常生活技能",
      questions: [
        {
          id: "sc_0_3_1",
          text: "能用杯子喝水（有溢出）",
          type: "scale",
          ageRange: [10, 18],
          standardRef: "Vineland量表",
          weight: 2,
        },
        {
          id: "sc_0_3_2",
          text: "能用勺子自己吃饭（有掉落）",
          type: "scale",
          ageRange: [12, 24],
          standardRef: "Vineland量表",
          weight: 2,
        },
        {
          id: "sc_0_3_3",
          text: "能脱掉简单衣物（如袜子）",
          type: "yesno",
          ageRange: [18, 30],
          standardRef: "CDC里程碑",
          weight: 1,
        },
        {
          id: "sc_0_3_4",
          text: "能表示大小便需求",
          type: "scale",
          ageRange: [18, 36],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "sc_0_3_5",
          text: "白天能基本控制大小便",
          type: "scale",
          ageRange: [24, 42],
          standardRef: "AAP指南",
          weight: 2,
        },
        {
          id: "sc_0_3_6",
          text: "能穿简单衣物（如套头衫）",
          type: "yesno",
          ageRange: [30, 42],
          standardRef: "Vineland量表",
          weight: 1,
        },
        {
          id: "sc_0_3_7",
          text: "能独立洗手（需提醒）",
          type: "scale",
          ageRange: [30, 42],
          standardRef: "CDC里程碑",
          weight: 1,
        },
      ],
    },
  ],
}

// 3-6岁 游戏化学习期评估题库
export const ASSESSMENT_3_6: StageAssessment = {
  stageId: "3-6",
  stageName: "游戏化学习期",
  dimensions: [
    {
      id: "cognitive",
      name: "认知发展",
      icon: "ri-brain-line",
      color: "blue",
      description: "思维、记忆、注意力发展",
      questions: [
        {
          id: "cog_3_6_1",
          text: "能够按颜色、形状或大小分类物品",
          type: "scale",
          ageRange: [36, 48],
          standardRef: "Bayley量表",
          weight: 2,
        },
        {
          id: "cog_3_6_2",
          text: "能够数数到10",
          type: "scale",
          ageRange: [36, 54],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "cog_3_6_3",
          text: '能够理解"一样多/更多/更少"',
          type: "scale",
          ageRange: [42, 60],
          standardRef: "Get Ready to Read",
          weight: 2,
        },
        {
          id: "cog_3_6_4",
          text: "能够说出基本形状名称（圆形、方形、三角形）",
          type: "yesno",
          ageRange: [42, 60],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "cog_3_6_5",
          text: "能够理解时间概念（今天、明天、昨天）",
          type: "scale",
          ageRange: [48, 66],
          standardRef: "学前准备评估",
          weight: 2,
        },
        {
          id: "cog_3_6_6",
          text: "能够专注于一项活动15分钟以上",
          type: "scale",
          ageRange: [48, 72],
          standardRef: "BRIEF-P",
          weight: 3,
        },
        {
          id: "cog_3_6_7",
          text: "能够按顺序排列3-5个事件或图片",
          type: "scale",
          ageRange: [54, 72],
          standardRef: "学前准备评估",
          weight: 2,
        },
        {
          id: "cog_3_6_8",
          text: "能够进行简单的加减运算（5以内）",
          type: "yesno",
          ageRange: [60, 78],
          standardRef: "数学准备评估",
          weight: 2,
        },
      ],
    },
    {
      id: "language",
      name: "语言能力",
      icon: "ri-chat-3-line",
      color: "green",
      description: "表达和理解语言的能力",
      questions: [
        {
          id: "lang_3_6_1",
          text: "能够清楚说出完整句子（5个字以上）",
          type: "scale",
          ageRange: [36, 48],
          standardRef: "CDC里程碑",
          weight: 3,
        },
        {
          id: "lang_3_6_2",
          text: "能够讲述简单的故事或经历",
          type: "scale",
          ageRange: [42, 60],
          standardRef: "MacArthur量表",
          weight: 2,
        },
        {
          id: "lang_3_6_3",
          text: "能够理解并执行三步指令",
          type: "scale",
          ageRange: [48, 66],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "lang_3_6_4",
          text: '能够使用"因为""所以"等连接词',
          type: "yesno",
          ageRange: [48, 66],
          standardRef: "语言发展标准",
          weight: 2,
        },
        {
          id: "lang_3_6_5",
          text: "能够认识常见汉字或字母",
          type: "scale",
          ageRange: [54, 72],
          standardRef: "Get Ready to Read",
          weight: 2,
        },
        {
          id: "lang_3_6_6",
          text: "能够书写自己的名字",
          type: "yesno",
          ageRange: [60, 78],
          standardRef: "学前准备评估",
          weight: 2,
        },
        {
          id: "lang_3_6_7",
          text: '能够理解并回答"为什么"类问题',
          type: "scale",
          ageRange: [48, 72],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "lang_3_6_8",
          text: "发音清晰，陌生人能听懂90%以上",
          type: "scale",
          ageRange: [54, 72],
          standardRef: "语言发展标准",
          weight: 3,
        },
      ],
    },
    {
      id: "social",
      name: "社交能力",
      icon: "ri-team-line",
      color: "purple",
      description: "人际交往和合作能力",
      questions: [
        {
          id: "soc_3_6_1",
          text: "能够主动与其他小朋友玩耍",
          type: "scale",
          ageRange: [36, 54],
          standardRef: "Devereux量表",
          weight: 2,
        },
        {
          id: "soc_3_6_2",
          text: "能够分享玩具和物品",
          type: "scale",
          ageRange: [36, 60],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "soc_3_6_3",
          text: "能够在游戏中轮流等待",
          type: "scale",
          ageRange: [42, 60],
          standardRef: "Devereux量表",
          weight: 3,
        },
        {
          id: "soc_3_6_4",
          text: "能够遵守简单的游戏规则",
          type: "scale",
          ageRange: [48, 66],
          standardRef: "CDC里程碑",
          weight: 2,
        },
        {
          id: "soc_3_6_5",
          text: "能够在冲突中寻求帮助或尝试解决",
          type: "scale",
          ageRange: [48, 72],
          standardRef: "Devereux量表",
          weight: 2,
        },
        {
          id: "soc_3_6_6",
          text: "能够理解他人的感受",
          type: "scale",
          ageRange: [54, 72],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "soc_3_6_7",
          text: "能够交到固定的朋友",
          type: "yesno",
          ageRange: [48, 72],
          standardRef: "社交发展标准",
          weight: 2,
        },
        {
          id: "soc_3_6_8",
          text: "能够在集体活动中配合他人",
          type: "scale",
          ageRange: [54, 78],
          standardRef: "学前准备评估",
          weight: 2,
        },
      ],
    },
    {
      id: "emotional",
      name: "情绪管理",
      icon: "ri-heart-pulse-line",
      color: "pink",
      description: "情绪识别和调节能力",
      questions: [
        {
          id: "emo_3_6_1",
          text: "能够识别基本情绪（开心、难过、生气）",
          type: "scale",
          ageRange: [36, 54],
          standardRef: "ERC量表",
          weight: 2,
        },
        {
          id: "emo_3_6_2",
          text: "能够用语言表达自己的情绪",
          type: "scale",
          ageRange: [36, 60],
          standardRef: "ASQ-SE",
          weight: 3,
        },
        {
          id: "emo_3_6_3",
          text: "能够在安慰下平复情绪",
          type: "scale",
          ageRange: [36, 60],
          standardRef: "ERC量表",
          weight: 2,
        },
        {
          id: "emo_3_6_4",
          text: "能够延迟满足（等待5分钟以上）",
          type: "scale",
          ageRange: [42, 66],
          standardRef: "BRIEF-P",
          weight: 3,
        },
        {
          id: "emo_3_6_5",
          text: "发脾气的频率和强度在可控范围",
          type: "scale",
          ageRange: [36, 72],
          standardRef: "ASQ-SE",
          weight: 2,
        },
        {
          id: "emo_3_6_6",
          text: "能够使用简单策略调节情绪（深呼吸、求助）",
          type: "scale",
          ageRange: [54, 78],
          standardRef: "ERC量表",
          weight: 2,
        },
        {
          id: "emo_3_6_7",
          text: "能够适应新环境（幼儿园、新朋友）",
          type: "scale",
          ageRange: [36, 72],
          standardRef: "ASQ-SE",
          weight: 2,
        },
      ],
    },
    {
      id: "motor",
      name: "运动发展",
      icon: "ri-run-line",
      color: "orange",
      description: "大运动和精细运动能力",
      questions: [
        { id: "mot_3_6_1", text: "能够单脚跳", type: "yesno", ageRange: [42, 60], standardRef: "CDC里程碑", weight: 2 },
        {
          id: "mot_3_6_2",
          text: "能够接住抛来的球",
          type: "scale",
          ageRange: [48, 66],
          standardRef: "运动发展评估",
          weight: 2,
        },
        {
          id: "mot_3_6_3",
          text: "能够骑三轮车或平衡车",
          type: "yesno",
          ageRange: [42, 60],
          standardRef: "CDC里程碑",
          weight: 1,
        },
        {
          id: "mot_3_6_4",
          text: "能够使用剪刀沿线剪纸",
          type: "scale",
          ageRange: [48, 66],
          standardRef: "Bayley量表",
          weight: 2,
        },
        {
          id: "mot_3_6_5",
          text: "能够画出人物（有头、身体、四肢）",
          type: "scale",
          ageRange: [48, 72],
          standardRef: "画人测验",
          weight: 2,
        },
        {
          id: "mot_3_6_6",
          text: "能够正确握笔写字",
          type: "scale",
          ageRange: [54, 78],
          standardRef: "书写准备评估",
          weight: 2,
        },
        {
          id: "mot_3_6_7",
          text: "能够系简单的扣子",
          type: "yesno",
          ageRange: [54, 72],
          standardRef: "Vineland量表",
          weight: 1,
        },
        {
          id: "mot_3_6_8",
          text: "能够独立上下楼梯（交替脚）",
          type: "scale",
          ageRange: [36, 54],
          standardRef: "CDC里程碑",
          weight: 2,
        },
      ],
    },
    {
      id: "creativity",
      name: "创造力",
      icon: "ri-lightbulb-flash-line",
      color: "yellow",
      description: "想象力和创造性思维",
      questions: [
        {
          id: "cre_3_6_1",
          text: "喜欢进行角色扮演游戏",
          type: "scale",
          ageRange: [36, 60],
          standardRef: "Torrance量表",
          weight: 2,
        },
        {
          id: "cre_3_6_2",
          text: "能够用积木或材料创建新事物",
          type: "scale",
          ageRange: [36, 66],
          standardRef: "创造力评估",
          weight: 2,
        },
        {
          id: "cre_3_6_3",
          text: "绘画时能加入自己的想法",
          type: "scale",
          ageRange: [42, 72],
          standardRef: "Torrance量表",
          weight: 2,
        },
        {
          id: "cre_3_6_4",
          text: "能够编造简单的故事",
          type: "scale",
          ageRange: [48, 72],
          standardRef: "创造力评估",
          weight: 2,
        },
        {
          id: "cre_3_6_5",
          text: "能够想出物品的多种用途",
          type: "scale",
          ageRange: [54, 78],
          standardRef: "Torrance量表",
          weight: 2,
        },
        {
          id: "cre_3_6_6",
          text: "对新事物充满好奇心",
          type: "scale",
          ageRange: [36, 72],
          standardRef: "好奇心量表",
          weight: 2,
        },
      ],
    },
  ],
}

// 6-9岁 学术奠基期评估题库
export const ASSESSMENT_6_9: StageAssessment = {
  stageId: "6-9",
  stageName: "学术奠基期",
  dimensions: [
    {
      id: "academic_language",
      name: "语文能力",
      icon: "ri-book-read-line",
      color: "blue",
      description: "阅读、写作和理解能力",
      questions: [
        {
          id: "al_6_9_1",
          text: "能够流利朗读课文",
          type: "scale",
          ageRange: [72, 96],
          standardRef: "小学语文标准",
          weight: 3,
        },
        {
          id: "al_6_9_2",
          text: "能够理解课文主要内容",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "阅读理解评估",
          weight: 3,
        },
        {
          id: "al_6_9_3",
          text: "能够正确书写所学汉字",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "书写评估",
          weight: 2,
        },
        {
          id: "al_6_9_4",
          text: "能够独立完成看图写话或短文",
          type: "scale",
          ageRange: [78, 108],
          standardRef: "写作评估",
          weight: 2,
        },
        {
          id: "al_6_9_5",
          text: "能够使用字典查字",
          type: "yesno",
          ageRange: [84, 108],
          standardRef: "学习技能评估",
          weight: 1,
        },
        {
          id: "al_6_9_6",
          text: "喜欢阅读课外书籍",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "阅读兴趣量表",
          weight: 2,
        },
      ],
    },
    {
      id: "academic_math",
      name: "数学能力",
      icon: "ri-calculator-line",
      color: "green",
      description: "数学运算和逻辑思维",
      questions: [
        {
          id: "am_6_9_1",
          text: "能够进行100以内的加减法",
          type: "scale",
          ageRange: [72, 96],
          standardRef: "小学数学标准",
          weight: 3,
        },
        {
          id: "am_6_9_2",
          text: "能够背诵乘法口诀",
          type: "scale",
          ageRange: [84, 108],
          standardRef: "小学数学标准",
          weight: 2,
        },
        {
          id: "am_6_9_3",
          text: "能够理解和解决简单应用题",
          type: "scale",
          ageRange: [78, 108],
          standardRef: "数学问题解决评估",
          weight: 3,
        },
        {
          id: "am_6_9_4",
          text: "能够认识常见的平面图形和立体图形",
          type: "scale",
          ageRange: [72, 96],
          standardRef: "几何认知评估",
          weight: 2,
        },
        {
          id: "am_6_9_5",
          text: "能够进行简单的估算",
          type: "scale",
          ageRange: [84, 108],
          standardRef: "数感评估",
          weight: 2,
        },
        {
          id: "am_6_9_6",
          text: "能够理解分数的基本概念",
          type: "scale",
          ageRange: [96, 114],
          standardRef: "小学数学标准",
          weight: 2,
        },
      ],
    },
    {
      id: "learning_habits",
      name: "学习习惯",
      icon: "ri-time-line",
      color: "purple",
      description: "学习态度和习惯养成",
      questions: [
        {
          id: "lh_6_9_1",
          text: "能够按时完成作业",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "学习习惯量表",
          weight: 3,
        },
        {
          id: "lh_6_9_2",
          text: "能够整理书包和学习用品",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "自我管理评估",
          weight: 2,
        },
        {
          id: "lh_6_9_3",
          text: "能够在课堂上专注听讲",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "注意力评估",
          weight: 3,
        },
        {
          id: "lh_6_9_4",
          text: "遇到不懂的问题会主动提问",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "学习习惯量表",
          weight: 2,
        },
        {
          id: "lh_6_9_5",
          text: "能够制定简单的学习计划",
          type: "scale",
          ageRange: [84, 114],
          standardRef: "自我管理评估",
          weight: 2,
        },
        {
          id: "lh_6_9_6",
          text: "对学习有内在兴趣",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "学习动机量表",
          weight: 2,
        },
      ],
    },
    {
      id: "social_school",
      name: "学校社交",
      icon: "ri-user-smile-line",
      color: "orange",
      description: "学校适应和同伴关系",
      questions: [
        {
          id: "ss_6_9_1",
          text: "能够适应学校生活规律",
          type: "scale",
          ageRange: [72, 96],
          standardRef: "学校适应量表",
          weight: 3,
        },
        {
          id: "ss_6_9_2",
          text: "有固定的好朋友",
          type: "yesno",
          ageRange: [72, 108],
          standardRef: "社交关系评估",
          weight: 2,
        },
        {
          id: "ss_6_9_3",
          text: "能够与同学合作完成任务",
          type: "scale",
          ageRange: [78, 108],
          standardRef: "合作能力评估",
          weight: 2,
        },
        {
          id: "ss_6_9_4",
          text: "能够遵守班级规则",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "行为规范评估",
          weight: 2,
        },
        {
          id: "ss_6_9_5",
          text: "与老师关系良好",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "师生关系评估",
          weight: 2,
        },
        {
          id: "ss_6_9_6",
          text: "能够处理同伴间的小矛盾",
          type: "scale",
          ageRange: [84, 114],
          standardRef: "冲突解决评估",
          weight: 2,
        },
      ],
    },
    {
      id: "self_management",
      name: "自我管理",
      icon: "ri-shield-user-line",
      color: "teal",
      description: "独立性和责任感",
      questions: [
        {
          id: "sm_6_9_1",
          text: "能够独立完成日常起居（洗漱、穿衣）",
          type: "scale",
          ageRange: [72, 96],
          standardRef: "生活自理评估",
          weight: 2,
        },
        {
          id: "sm_6_9_2",
          text: "能够管理自己的物品",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "自我管理评估",
          weight: 2,
        },
        {
          id: "sm_6_9_3",
          text: "能够按时起床睡觉",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "作息习惯评估",
          weight: 2,
        },
        {
          id: "sm_6_9_4",
          text: "有基本的安全意识",
          type: "scale",
          ageRange: [72, 108],
          standardRef: "安全认知评估",
          weight: 3,
        },
        {
          id: "sm_6_9_5",
          text: "能够承担简单的家务",
          type: "scale",
          ageRange: [84, 114],
          standardRef: "责任感评估",
          weight: 1,
        },
        {
          id: "sm_6_9_6",
          text: "能够管理零花钱",
          type: "scale",
          ageRange: [84, 114],
          standardRef: "财务启蒙评估",
          weight: 1,
        },
      ],
    },
  ],
}

// 9-12岁 思维建构期评估题库
export const ASSESSMENT_9_12: StageAssessment = {
  stageId: "9-12",
  stageName: "思维建构期",
  dimensions: [
    {
      id: "logical_thinking",
      name: "逻辑思维",
      icon: "ri-mind-map",
      color: "blue",
      description: "抽象思维和逻辑推理能力",
      questions: [
        {
          id: "lt_9_12_1",
          text: "能够进行多步骤数学运算",
          type: "scale",
          ageRange: [108, 132],
          standardRef: "数学思维评估",
          weight: 3,
        },
        {
          id: "lt_9_12_2",
          text: "能够理解因果关系并做出推断",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "认知发展评估",
          weight: 3,
        },
        {
          id: "lt_9_12_3",
          text: "能够从多角度分析问题",
          type: "scale",
          ageRange: [114, 144],
          standardRef: "批判性思维评估",
          weight: 2,
        },
        {
          id: "lt_9_12_4",
          text: "能够进行简单的科学实验并记录",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "科学探究评估",
          weight: 2,
        },
        {
          id: "lt_9_12_5",
          text: "能够理解抽象概念（如比例、负数）",
          type: "scale",
          ageRange: [120, 150],
          standardRef: "数学抽象评估",
          weight: 3,
        },
        {
          id: "lt_9_12_6",
          text: "能够进行分类、归纳和总结",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "逻辑推理评估",
          weight: 2,
        },
      ],
    },
    {
      id: "academic_advanced",
      name: "学业能力",
      icon: "ri-graduation-cap-line",
      color: "green",
      description: "各学科综合学习能力",
      questions: [
        {
          id: "aa_9_12_1",
          text: "能够独立阅读并理解较长篇幅的文章",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "阅读理解评估",
          weight: 3,
        },
        {
          id: "aa_9_12_2",
          text: "能够撰写结构完整的作文",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "写作评估",
          weight: 3,
        },
        {
          id: "aa_9_12_3",
          text: "英语基础词汇量达到年级要求",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "英语能力评估",
          weight: 2,
        },
        {
          id: "aa_9_12_4",
          text: "能够解决综合性数学应用题",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "数学应用评估",
          weight: 3,
        },
        {
          id: "aa_9_12_5",
          text: "能够进行简单的英语对话",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "英语口语评估",
          weight: 2,
        },
        {
          id: "aa_9_12_6",
          text: "对科学知识有好奇心和探索欲",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "科学兴趣量表",
          weight: 2,
        },
      ],
    },
    {
      id: "self_regulation",
      name: "自我调节",
      icon: "ri-mental-health-line",
      color: "purple",
      description: "情绪管理和自我控制能力",
      questions: [
        {
          id: "sr_9_12_1",
          text: "能够识别复杂情绪（焦虑、嫉妒、挫败）",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "情绪智力评估",
          weight: 2,
        },
        {
          id: "sr_9_12_2",
          text: "能够有效管理学习压力",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "压力管理评估",
          weight: 3,
        },
        {
          id: "sr_9_12_3",
          text: "面对挫折能够坚持尝试",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "抗挫力评估",
          weight: 3,
        },
        {
          id: "sr_9_12_4",
          text: "能够控制冲动行为",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "自控力评估",
          weight: 2,
        },
        {
          id: "sr_9_12_5",
          text: "能够设定并追求短期目标",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "目标管理评估",
          weight: 2,
        },
        {
          id: "sr_9_12_6",
          text: "能够反思自己的行为和表现",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "元认知评估",
          weight: 2,
        },
      ],
    },
    {
      id: "social_complex",
      name: "复杂社交",
      icon: "ri-team-line",
      color: "orange",
      description: "深层次的人际交往能力",
      questions: [
        {
          id: "sc_9_12_1",
          text: "能够建立和维护深厚的友谊",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "友谊质量评估",
          weight: 2,
        },
        {
          id: "sc_9_12_2",
          text: "能够理解社交中的复杂情境",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "社交认知评估",
          weight: 2,
        },
        {
          id: "sc_9_12_3",
          text: "能够在团队中发挥积极作用",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "团队合作评估",
          weight: 2,
        },
        {
          id: "sc_9_12_4",
          text: "能够处理同伴压力",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "同伴影响评估",
          weight: 3,
        },
        {
          id: "sc_9_12_5",
          text: "能够表达不同意见并尊重他人",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "沟通能力评估",
          weight: 2,
        },
        {
          id: "sc_9_12_6",
          text: "能够识别并应对不良社交行为",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "社交安全评估",
          weight: 3,
        },
      ],
    },
    {
      id: "creativity_innovation",
      name: "创新创造",
      icon: "ri-lightbulb-flash-line",
      color: "yellow",
      description: "创造力和创新思维",
      questions: [
        {
          id: "ci_9_12_1",
          text: "能够提出独特的问题解决方案",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "创造力评估",
          weight: 2,
        },
        {
          id: "ci_9_12_2",
          text: "有自己的兴趣爱好并深入发展",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "兴趣发展评估",
          weight: 2,
        },
        {
          id: "ci_9_12_3",
          text: "能够进行创意写作或艺术创作",
          type: "scale",
          ageRange: [108, 144],
          standardRef: "艺术创造评估",
          weight: 2,
        },
        {
          id: "ci_9_12_4",
          text: "对科技和编程有兴趣",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "科技兴趣量表",
          weight: 1,
        },
        {
          id: "ci_9_12_5",
          text: "能够独立完成项目式学习任务",
          type: "scale",
          ageRange: [114, 150],
          standardRef: "项目能力评估",
          weight: 2,
        },
      ],
    },
  ],
}

// 12-15岁 青春转型期评估题库
export const ASSESSMENT_12_15: StageAssessment = {
  stageId: "12-15",
  stageName: "青春转型期",
  dimensions: [
    {
      id: "identity_development",
      name: "自我认同",
      icon: "ri-user-search-line",
      color: "blue",
      description: "自我认知和身份探索",
      questions: [
        {
          id: "id_12_15_1",
          text: "能够客观评价自己的优缺点",
          type: "scale",
          ageRange: [144, 180],
          standardRef: "自我认知评估",
          weight: 3,
        },
        {
          id: "id_12_15_2",
          text: "对未来有初步的想法和规划",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "生涯发展评估",
          weight: 2,
        },
        {
          id: "id_12_15_3",
          text: "能够接受身体发育带来的变化",
          type: "scale",
          ageRange: [144, 180],
          standardRef: "青春期适应评估",
          weight: 3,
        },
        {
          id: "id_12_15_4",
          text: "有明确的兴趣和爱好方向",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "兴趣定向评估",
          weight: 2,
        },
        {
          id: "id_12_15_5",
          text: "能够形成自己的价值观和判断",
          type: "scale",
          ageRange: [156, 186],
          standardRef: "价值观发展评估",
          weight: 2,
        },
        {
          id: "id_12_15_6",
          text: "对自己的身份认同感到舒适",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "身份认同评估",
          weight: 3,
        },
      ],
    },
    {
      id: "academic_middle",
      name: "学业发展",
      icon: "ri-book-open-line",
      color: "green",
      description: "初中阶段学业能力",
      questions: [
        {
          id: "am_12_15_1",
          text: "能够掌握各学科核心知识",
          type: "scale",
          ageRange: [144, 180],
          standardRef: "学业成就评估",
          weight: 3,
        },
        {
          id: "am_12_15_2",
          text: "能够自主制定学习计划",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "学习自主性评估",
          weight: 3,
        },
        {
          id: "am_12_15_3",
          text: "能够高效利用学习时间",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "时间管理评估",
          weight: 2,
        },
        {
          id: "am_12_15_4",
          text: "能够独立完成研究性学习",
          type: "scale",
          ageRange: [156, 186],
          standardRef: "研究能力评估",
          weight: 2,
        },
        {
          id: "am_12_15_5",
          text: "对某些学科有特别的兴趣",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "学科兴趣评估",
          weight: 2,
        },
        {
          id: "am_12_15_6",
          text: "能够应对考试压力",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "考试焦虑评估",
          weight: 3,
        },
      ],
    },
    {
      id: "emotional_adolescent",
      name: "情绪健康",
      icon: "ri-heart-pulse-line",
      color: "pink",
      description: "青春期情绪管理",
      questions: [
        {
          id: "ea_12_15_1",
          text: "能够觉察和表达复杂情绪",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "情绪觉察评估",
          weight: 2,
        },
        {
          id: "ea_12_15_2",
          text: "能够健康地处理青春期情绪波动",
          type: "scale",
          ageRange: [144, 180],
          standardRef: "情绪调节评估",
          weight: 3,
        },
        {
          id: "ea_12_15_3",
          text: "有信任的人可以倾诉",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "社会支持评估",
          weight: 3,
        },
        {
          id: "ea_12_15_4",
          text: "能够识别负面情绪的来源",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "情绪智力评估",
          weight: 2,
        },
        {
          id: "ea_12_15_5",
          text: "有健康的压力释放方式",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "压力应对评估",
          weight: 2,
        },
        {
          id: "ea_12_15_6",
          text: "对生活保持积极态度",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "心理健康评估",
          weight: 3,
        },
      ],
    },
    {
      id: "social_peer",
      name: "同伴关系",
      icon: "ri-group-line",
      color: "purple",
      description: "同龄人交往能力",
      questions: [
        {
          id: "sp_12_15_1",
          text: "有稳定的朋友圈",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "同伴关系评估",
          weight: 2,
        },
        {
          id: "sp_12_15_2",
          text: "能够健康看待异性关系",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "性别意识评估",
          weight: 3,
        },
        {
          id: "sp_12_15_3",
          text: "能够抵制不良同伴影响",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "同伴压力评估",
          weight: 3,
        },
        {
          id: "sp_12_15_4",
          text: "能够在集体中发挥作用",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "领导力评估",
          weight: 2,
        },
        {
          id: "sp_12_15_5",
          text: "能够处理复杂的人际冲突",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "冲突解决评估",
          weight: 2,
        },
        {
          id: "sp_12_15_6",
          text: "能够维护健康的网络社交",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "网络素养评估",
          weight: 3,
        },
      ],
    },
    {
      id: "family_independence",
      name: "家庭独立",
      icon: "ri-home-heart-line",
      color: "orange",
      description: "家庭关系与独立性发展",
      questions: [
        {
          id: "fi_12_15_1",
          text: "能够与父母有效沟通",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "亲子沟通评估",
          weight: 3,
        },
        {
          id: "fi_12_15_2",
          text: "在适当范围内寻求独立",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "自主性发展评估",
          weight: 2,
        },
        {
          id: "fi_12_15_3",
          text: "能够承担家庭责任",
          type: "scale",
          ageRange: [150, 186],
          standardRef: "责任感评估",
          weight: 2,
        },
        {
          id: "fi_12_15_4",
          text: "尊重家庭规则的同时表达自我",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "界限感评估",
          weight: 2,
        },
        {
          id: "fi_12_15_5",
          text: "能够平衡学业与家庭生活",
          type: "scale",
          ageRange: [144, 186],
          standardRef: "生活平衡评估",
          weight: 2,
        },
      ],
    },
  ],
}

// 15-18岁 生涯定位期评估题库
export const ASSESSMENT_15_18: StageAssessment = {
  stageId: "15-18",
  stageName: "生涯定位期",
  dimensions: [
    {
      id: "career_exploration",
      name: "生涯探索",
      icon: "ri-compass-3-line",
      color: "blue",
      description: "职业方向和未来规划",
      questions: [
        {
          id: "ce_15_18_1",
          text: "对未来职业方向有初步想法",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "职业兴趣评估",
          weight: 3,
        },
        {
          id: "ce_15_18_2",
          text: "了解自己的优势和发展方向",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "自我认知评估",
          weight: 3,
        },
        {
          id: "ce_15_18_3",
          text: "主动了解感兴趣的专业和职业",
          type: "scale",
          ageRange: [186, 222],
          standardRef: "生涯探索评估",
          weight: 2,
        },
        {
          id: "ce_15_18_4",
          text: "能够将学习与未来目标联系",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "目标导向评估",
          weight: 2,
        },
        {
          id: "ce_15_18_5",
          text: "有实践或志愿者经历",
          type: "yesno",
          ageRange: [186, 222],
          standardRef: "社会实践评估",
          weight: 1,
        },
        {
          id: "ce_15_18_6",
          text: "能够制定高中及之后的学业规划",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "规划能力评估",
          weight: 3,
        },
      ],
    },
    {
      id: "academic_high",
      name: "学业准备",
      icon: "ri-graduation-cap-line",
      color: "green",
      description: "高中学业与升学准备",
      questions: [
        {
          id: "ah_15_18_1",
          text: "能够自主深入学习感兴趣的学科",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "学习深度评估",
          weight: 3,
        },
        {
          id: "ah_15_18_2",
          text: "能够有效准备重要考试",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "考试准备评估",
          weight: 3,
        },
        {
          id: "ah_15_18_3",
          text: "能够进行跨学科思考",
          type: "scale",
          ageRange: [186, 222],
          standardRef: "综合思维评估",
          weight: 2,
        },
        {
          id: "ah_15_18_4",
          text: "有学科竞赛或特长发展",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "特长发展评估",
          weight: 2,
        },
        {
          id: "ah_15_18_5",
          text: "能够独立完成研究性课题",
          type: "scale",
          ageRange: [186, 222],
          standardRef: "研究能力评估",
          weight: 2,
        },
        {
          id: "ah_15_18_6",
          text: "有明确的升学目标",
          type: "scale",
          ageRange: [192, 222],
          standardRef: "升学规划评估",
          weight: 3,
        },
      ],
    },
    {
      id: "critical_thinking",
      name: "批判思维",
      icon: "ri-brain-line",
      color: "purple",
      description: "独立思考和批判性思维",
      questions: [
        {
          id: "ct_15_18_1",
          text: "能够质疑和分析信息来源",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "批判性思维评估",
          weight: 3,
        },
        {
          id: "ct_15_18_2",
          text: "能够进行多角度辩证思考",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "辩证思维评估",
          weight: 2,
        },
        {
          id: "ct_15_18_3",
          text: "能够形成并表达独立观点",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "独立思考评估",
          weight: 3,
        },
        {
          id: "ct_15_18_4",
          text: "能够进行逻辑论证",
          type: "scale",
          ageRange: [186, 222],
          standardRef: "逻辑推理评估",
          weight: 2,
        },
        {
          id: "ct_15_18_5",
          text: "对社会问题有自己的思考",
          type: "scale",
          ageRange: [186, 222],
          standardRef: "社会认知评估",
          weight: 2,
        },
      ],
    },
    {
      id: "responsibility",
      name: "责任担当",
      icon: "ri-shield-star-line",
      color: "orange",
      description: "社会责任和公民意识",
      questions: [
        {
          id: "re_15_18_1",
          text: "有社会责任感和公民意识",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "公民素养评估",
          weight: 2,
        },
        {
          id: "re_15_18_2",
          text: "关心社会问题和时事",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "社会关注评估",
          weight: 2,
        },
        {
          id: "re_15_18_3",
          text: "能够独立做出负责任的决定",
          type: "scale",
          ageRange: [186, 222],
          standardRef: "决策能力评估",
          weight: 3,
        },
        {
          id: "re_15_18_4",
          text: "参与志愿服务或公益活动",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "公益参与评估",
          weight: 1,
        },
        {
          id: "re_15_18_5",
          text: "有明确的道德底线和原则",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "道德发展评估",
          weight: 3,
        },
      ],
    },
    {
      id: "life_skills",
      name: "生活技能",
      icon: "ri-tools-line",
      color: "teal",
      description: "独立生活准备",
      questions: [
        {
          id: "ls_15_18_1",
          text: "具备基本的理财意识",
          type: "scale",
          ageRange: [180, 216],
          standardRef: "财务素养评估",
          weight: 2,
        },
        {
          id: "ls_15_18_2",
          text: "能够照顾自己的基本生活",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "生活自理评估",
          weight: 2,
        },
        {
          id: "ls_15_18_3",
          text: "有健康的生活方式",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "健康行为评估",
          weight: 3,
        },
        {
          id: "ls_15_18_4",
          text: "能够有效管理时间",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "时间管理评估",
          weight: 3,
        },
        {
          id: "ls_15_18_5",
          text: "具备基本的安全和法律意识",
          type: "scale",
          ageRange: [180, 222],
          standardRef: "安全法律意识评估",
          weight: 3,
        },
      ],
    },
  ],
}

// 18-22岁 成人成才期评估题库
export const ASSESSMENT_18_22: StageAssessment = {
  stageId: "18-22",
  stageName: "成人成才期",
  dimensions: [
    {
      id: "independence",
      name: "独立发展",
      icon: "ri-rocket-line",
      color: "blue",
      description: "独立生活与自我发展",
      questions: [
        {
          id: "ind_18_22_1",
          text: "能够独立处理日常生活事务",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "独立生活评估",
          weight: 3,
        },
        {
          id: "ind_18_22_2",
          text: "有明确的人生目标和方向",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "人生规划评估",
          weight: 3,
        },
        {
          id: "ind_18_22_3",
          text: "能够自主做出重大决定",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "决策自主评估",
          weight: 3,
        },
        {
          id: "ind_18_22_4",
          text: "有持续学习和成长的意愿",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "终身学习评估",
          weight: 2,
        },
        {
          id: "ind_18_22_5",
          text: "能够有效管理个人财务",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "财务管理评估",
          weight: 2,
        },
      ],
    },
    {
      id: "career_development",
      name: "职业发展",
      icon: "ri-briefcase-4-line",
      color: "green",
      description: "职业能力与就业准备",
      questions: [
        {
          id: "cd_18_22_1",
          text: "具备专业领域的核心能力",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "专业能力评估",
          weight: 3,
        },
        {
          id: "cd_18_22_2",
          text: "有实习或工作经验",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "职业经历评估",
          weight: 2,
        },
        {
          id: "cd_18_22_3",
          text: "具备基本的职场沟通能力",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "职场沟通评估",
          weight: 3,
        },
        {
          id: "cd_18_22_4",
          text: "了解目标行业的发展趋势",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "行业认知评估",
          weight: 2,
        },
        {
          id: "cd_18_22_5",
          text: "有清晰的职业发展规划",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "职业规划评估",
          weight: 3,
        },
        {
          id: "cd_18_22_6",
          text: "具备求职所需的技能和准备",
          type: "scale",
          ageRange: [234, 270],
          standardRef: "求职准备评估",
          weight: 2,
        },
      ],
    },
    {
      id: "relationship_mature",
      name: "成熟关系",
      icon: "ri-heart-2-line",
      color: "pink",
      description: "亲密关系与社交网络",
      questions: [
        {
          id: "rm_18_22_1",
          text: "能够建立健康的亲密关系",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "亲密关系评估",
          weight: 3,
        },
        {
          id: "rm_18_22_2",
          text: "与家人保持良好关系",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "家庭关系评估",
          weight: 2,
        },
        {
          id: "rm_18_22_3",
          text: "有可靠的朋友和支持网络",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "社会支持评估",
          weight: 2,
        },
        {
          id: "rm_18_22_4",
          text: "能够有效处理人际冲突",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "冲突解决评估",
          weight: 2,
        },
        {
          id: "rm_18_22_5",
          text: "能够在关系中保持独立性",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "关系边界评估",
          weight: 2,
        },
      ],
    },
    {
      id: "mental_wellness",
      name: "心理健康",
      icon: "ri-mental-health-line",
      color: "purple",
      description: "心理适应与压力管理",
      questions: [
        {
          id: "mw_18_22_1",
          text: "能够有效管理生活压力",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "压力管理评估",
          weight: 3,
        },
        {
          id: "mw_18_22_2",
          text: "对自我有积极认同",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "自我认同评估",
          weight: 3,
        },
        {
          id: "mw_18_22_3",
          text: "有健康的情绪调节方式",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "情绪健康评估",
          weight: 2,
        },
        {
          id: "mw_18_22_4",
          text: "能够应对生活中的不确定性",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "适应能力评估",
          weight: 2,
        },
        {
          id: "mw_18_22_5",
          text: "有明确的价值观和人生意义",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "人生意义评估",
          weight: 3,
        },
      ],
    },
    {
      id: "social_contribution",
      name: "社会贡献",
      icon: "ri-earth-line",
      color: "orange",
      description: "社会参与与贡献",
      questions: [
        {
          id: "sc_18_22_1",
          text: "关心社会问题并积极参与",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "社会参与评估",
          weight: 2,
        },
        {
          id: "sc_18_22_2",
          text: "有回馈社会的意愿和行动",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "社会责任评估",
          weight: 2,
        },
        {
          id: "sc_18_22_3",
          text: "遵守社会规范和法律",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "公民责任评估",
          weight: 3,
        },
        {
          id: "sc_18_22_4",
          text: "具备全球视野和跨文化意识",
          type: "scale",
          ageRange: [222, 270],
          standardRef: "全球视野评估",
          weight: 2,
        },
        {
          id: "sc_18_22_5",
          text: "能够为所在群体做出贡献",
          type: "scale",
          ageRange: [216, 264],
          standardRef: "群体贡献评估",
          weight: 2,
        },
      ],
    },
  ],
}

// 阶段评估配置映射
export const STAGE_ASSESSMENTS: Record<string, StageAssessment> = {
  "0-3": ASSESSMENT_0_3,
  "3-6": ASSESSMENT_3_6,
  "6-9": ASSESSMENT_6_9,
  "9-12": ASSESSMENT_9_12,
  "12-15": ASSESSMENT_12_15,
  "15-18": ASSESSMENT_15_18,
  "18-22": ASSESSMENT_18_22,
}

// 根据月龄获取适用的问题
export function getApplicableQuestions(assessment: StageAssessment, ageInMonths: number): AssessmentDimension[] {
  return assessment.dimensions
    .map((dimension) => ({
      ...dimension,
      questions: dimension.questions.filter((q) => ageInMonths >= q.ageRange[0] && ageInMonths <= q.ageRange[1]),
    }))
    .filter((d) => d.questions.length > 0)
}

// 计算维度得分
export function calculateDimensionScore(answers: Record<string, number>, questions: AssessmentQuestion[]): number {
  const answeredQuestions = questions.filter((q) => answers[q.id] !== undefined)
  if (answeredQuestions.length === 0) return 0

  const totalWeight = answeredQuestions.reduce((sum, q) => sum + (q.weight || 1), 0)
  const weightedScore = answeredQuestions.reduce((sum, q) => {
    const score = answers[q.id]
    const weight = q.weight || 1
    const normalizedScore = q.type === "yesno" ? (score === 5 ? 100 : 0) : (score / 5) * 100
    return sum + normalizedScore * weight
  }, 0)

  return Math.round(weightedScore / totalWeight)
}

// 生成评估建议
export function generateRecommendations(dimensionScores: Record<string, number>, stageId: string): string[] {
  const recommendations: string[] = []
  const threshold = { excellent: 85, good: 70, concern: 50 }

  Object.entries(dimensionScores).forEach(([dimId, score]) => {
    if (score >= threshold.excellent) {
      recommendations.push(`${dimId}发展优秀，建议继续保持并尝试更高挑战`)
    } else if (score >= threshold.good) {
      recommendations.push(`${dimId}发展良好，可通过针对性活动进一步提升`)
    } else if (score >= threshold.concern) {
      recommendations.push(`${dimId}发展一般，建议增加相关训练和互动`)
    } else {
      recommendations.push(`${dimId}需要重点关注，建议咨询专业人士进行评估`)
    }
  })

  return recommendations
}
